festival/urls.py
from django.contrib import admin
from django.urls import path, include
from festival_app.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('', include('user_profiles.urls', namespace='user_profiles')),
    path('', include('festival_app.urls', namespace='festival_app')),
]

festival_app/urls.py
from django.urls import path
from festival_app.views import CreateApplication, ViewApplications, AppAcceptToggle, AppDeniedToggle, ErrorView, WayView,\
    ViewApplicationDetailCensor, AppLikeToggle, AppDislikeToggle, ViewApplicationDetailMusican, AppAbstainToggle

app_name = 'festival_app'

urlpatterns = [
    path('application-create', CreateApplication.as_view(), name='application-create'),
    path('view-applications', ViewApplications.as_view(), name='view-applications'),
    path('view-app-musican/<slug:slug>/', ViewApplicationDetailMusican.as_view(), name='view-app-musican'),
    path('view-app-censor/<slug:slug>/', ViewApplicationDetailCensor.as_view(), name='view-app-censor'),
    path('view-app-censor/<slug:slug>/abstain', AppAbstainToggle.as_view(), name='abstain'),
    path('view-app-censor/<slug:slug>/like', AppLikeToggle.as_view(), name='like'),
    path('view-app-censor/<slug:slug>/dislike', AppDislikeToggle.as_view(), name='dislike'),
    path('view-app-censor/<slug:slug>/accept', AppAcceptToggle.as_view(), name='accepted'),
    path('view-app-censor/<slug:slug>/denied', AppDeniedToggle.as_view(), name='denied'),
    path('error', ErrorView.as_view(), name='error'),
    path('way', WayView.as_view(), name='way'),
]

festival_app/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from slugify import slugify

from user_profiles.models import UserProfile



RED = 'RD'
BLUE = 'BL'
WATERMELON = 'WM'

SCENE_CHOICES = [
    (RED, 'Красная'),
    (BLUE, 'Синяя'),
    (WATERMELON, 'Арбузик'),
]

class Application(models.Model):
    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

    GROUP = 'GR'
    SOLO = 'SO'

    FORMAT_CHOICES = [
        (GROUP, 'Группа'),
        (SOLO, 'Сольное выступление'),
    ]

    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, allow_unicode=True, max_length=30)
    phone = models.CharField(max_length=12, verbose_name='Телефон')

    format = models.CharField(max_length=2, choices=FORMAT_CHOICES, verbose_name='Формат выступления')
    name = models.CharField(max_length=30, verbose_name='Имя группы или исполнителя', unique=True)
    description = models.TextField(verbose_name='Описание')
    likes = models.ManyToManyField(UserProfile, blank=True, related_name='likes', verbose_name='Нравится')
    dislikes = models.ManyToManyField(UserProfile, blank=True, related_name='dislikes', verbose_name='Не нравится')
    abstain = models.ManyToManyField(UserProfile, blank=True, related_name='abstain', verbose_name='Воздерживаюсь')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    accepted = models.BooleanField(default=False, verbose_name='Одобрено')
    denied = models.BooleanField(default=False, verbose_name='Отказано')
    scene = models.CharField(max_length=2, choices=SCENE_CHOICES, verbose_name='Желаемая сцена')

    FRIDAY = 'FR'
    SATURDAY = 'SA'

    DAY_CHOICES = [
        (FRIDAY, 'Пятница'),
        (SATURDAY, 'Суббота'),
    ]

    performance_day = models.CharField(max_length=2, choices=DAY_CHOICES, verbose_name='Желаемый день выступления')
    wishes = models.CharField(max_length=250, blank=True, verbose_name='Пожелания')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('festival_app:view-app-censor', kwargs={'slug': self.slug})


# Автоматическая генерация и установка слагов для заявок.


def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = slugify(new_slug)
    qs = Application.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_app_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_app_receiver, sender=Application)


# Автоматический подсчет рейтинга после каждого лайка/дизлайка.
def count_rating(slug):
    app = Application.objects.get(slug=slug)
    app.rating = app.likes.count() - app.dislikes.count()
    app.save()


# Автоматический вердикт для заявки, когда сумма голосов равна количеству цензоров. ( То есть проголосовали
# все цензоры )
def count_votes(slug):
    app = Application.objects.get(slug=slug)
    app_votes = app.likes.count() + app.dislikes.count() + app.abstain.count()
    censors_count = UserProfile.objects.filter(type='CE').count()
    if app_votes == censors_count:
        if app.likes.count() > app.dislikes.count():
            app.accepted = True
            app.save()
        if app.dislikes.count() > app.likes.count():
            app.denied = True
            app.save()
        if app.likes.count() == app.dislikes.count():
            app.denied = True
            app.save()


class Scene(models.Model):

    class Meta:
        verbose_name = 'Сцена'
        verbose_name_plural = 'Сцены'

    title = models.CharField(max_length=2, choices=SCENE_CHOICES, verbose_name='Название сцены')
    description = models.CharField(max_length=300, verbose_name='Описание сцены')
    first_day_afternoon = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день днём')
    first_day_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день вечером')
    first_day_late_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день поздним '
                                                                             'вечером')
    second_day_afternoon = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день днём')
    second_day_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день вечером')
    second_day_late_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день поздним '
                                                                              'вечером')

    def __str__(self):
        return self.title

festival_app/forms.py
from django import forms
from festival_app.models import Application




class CreateApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['format', 'name', 'description', 'phone', 'scene', 'performance_day', 'wishes']

festival_app/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView, ListView, DetailView, RedirectView
from festival_app.forms import CreateApplicationForm
from festival_app.models import Application, Scene, count_rating, count_votes
from user_profiles.models import UserProfile


class HomeView(TemplateView):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['scenes'] = Scene.objects.all()
        if self.request.user.is_anonymous:
            return context
        if self.request.user.is_authenticated:
            user = UserProfile.objects.get(user=self.request.user)
            if user.type == 'MU' and Application.objects.filter(user=user):
                context['app'] = Application.objects.get(user=user)
                return context
            if user.type == 'CE':
                context['censor'] = user
                return context
        return context


class ErrorView(TemplateView):
    template_name = 'error.html'


class WayView(TemplateView):
    template_name = 'way.html'


class CreateApplication(FormView):
    form_class = CreateApplicationForm
    template_name = 'application-create.html'
    success_url = reverse_lazy('home')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'MU':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        if Application.objects.filter(user=user):
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(CreateApplication, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = UserProfile.objects.get(user=self.request.user)
        instance.save()
        return super(CreateApplication, self).form_valid(form)


class ViewApplications(ListView):
    model = Application
    context_object_name = 'applications'
    template_name = 'view-applications.html'
    queryset = Application.objects.filter(denied=False)
    paginate_by = 5

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'CE':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(ViewApplications, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ViewApplications, self).get_context_data(**kwargs)
        context['accepted_apps'] = Application.objects.filter(accepted=True)
        context['unreviewed_apps'] = Application.objects.filter(accepted=False, denied=False)
        context['sum_unrw_apps'] = Application.objects.filter(accepted=False, denied=False).count()
        return context


class ViewApplicationDetailCensor(DetailView):
    model = Application
    template_name = 'view-app-detail-censor.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'CE':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(ViewApplicationDetailCensor, self).dispatch(request, *args, **kwargs)


class ViewApplicationDetailMusican(DetailView):
    model = Application
    template_name = 'view-app-detail-musican.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        slug = self.kwargs.get('slug')
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'MU':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        if user != Application.objects.get(slug=slug).user:
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(ViewApplicationDetailMusican, self).dispatch(request, *args, **kwargs)

 
    


class AppLikeToggle(RedirectView):
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'CE':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(AppLikeToggle, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Application, slug=slug)
        url_ = obj.get_absolute_url()
        user = UserProfile.objects.get(user=self.request.user)
        if user in obj.dislikes.all():
            obj.dislikes.remove(user)
        if user in obj.abstain.all():
            obj.abstain.remove(user)
        if user in obj.likes.all():
            obj.likes.remove(user)
        else:
            obj.likes.add(user)
        count_votes(slug)
        count_rating(slug)
        return url_


class AppDislikeToggle(RedirectView):

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'CE':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(AppDislikeToggle, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Application, slug=slug)
        url_ = obj.get_absolute_url()
        user = UserProfile.objects.get(user=self.request.user)
        if user in obj.likes.all():
            obj.likes.remove(user)
        if user in obj.abstain.all():
            obj.abstain.remove(user)
        if user in obj.dislikes.all():
            obj.dislikes.remove(user)
        else:
            obj.dislikes.add(user)
        count_votes(slug)
        count_rating(slug)
        return url_


class AppAbstainToggle(RedirectView):

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'CE':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(AppAbstainToggle, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Application, slug=slug)
        url_ = obj.get_absolute_url()
        user = UserProfile.objects.get(user=self.request.user)
        if user in obj.likes.all():
            obj.likes.remove(user)
        if user in obj.dislikes.all():
            obj.dislikes.remove(user)
        if user in obj.abstain.all():
            obj.abstain.remove(user)
        else:
            obj.abstain.add(user)
        count_votes(slug)
        count_rating(slug)
        return url_


class AppAcceptToggle(RedirectView):

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'CE':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(AppAcceptToggle, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Application, slug=slug)
        url_ = obj.get_absolute_url()
        if not obj.accepted:
            obj.accepted = True
            obj.save()
        return url_


class AppDeniedToggle(RedirectView):

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('user_profiles:login'))
        user = UserProfile.objects.get(user=self.request.user)
        if user.type != 'CE':
            return HttpResponseRedirect(reverse_lazy('festival_app:error'))
        else:
            return super(AppDeniedToggle, self).dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Application, slug=slug)
        url_ = obj.get_absolute_url()
        if not obj.denied:
            obj.denied = True
            obj.save()
        return url_

festival_app/templates/application-create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/app.css' %}">
<div class="container-fluild">
	<div class="app">
		<form method="post">
			{% csrf_token %}
			{% bootstrap_form form %}
			<button class="btn btn-primary" style="width:100%">Подать заявку</button>
		</form>
	</div>
</div>


{% endblock content %}

festival_app/templates/error.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/app.css' %}">
<div class="error">
    <h2>Упс! У вас нет доступа. </h2>
</div>
{% endblock content %}

festival_app/templates/view-app-detail-censor.html
{% extends 'base.html' %}
{% block content %}

{% load static%}
<link rel="stylesheet" href="{% static 'css/app.css' %}">

{% if application.accepted or application.denied %}
<div class="detail-app">
    <p>Имя группы или музыканта: {{ application.name }}</p>
    <p>Формат выступления: {{ application.get_format_display }}</p>
    <p>Подробное описание: {{ application.description }}</p>
</div>
{% else %}
<div class="detail-app">
    <p>Имя группы или музыканта: {{ application.name }}</p>
    <p>Формат выступления: {{ application.get_format_display }}</p>
    <p>Подробное описание: <br> {{ application.description }}</p>
    <a href="{% url 'festival_app:like' application.slug %}"><button type="button" class="btn btn-primary">Нравится {{ application.likes.count }} </button></a>
    {% if application.rating >= 3 %}
    <a href="{% url 'festival_app:accepted' application.slug %}"><button type="button" class="btn btn-primary">Одобрить</button></a>
    {% endif %}
    {% if application.dislikes >= 5 %}
    <a href="{% url 'festival_app:denied' application.slug %}"><button type="button" class="btn btn-primary">Отказать</button></a>
    {% endif %}
    <a href="{% url 'festival_app:abstain' application.slug %}"><button type="button" class="btn btn-primary">Воздержаться {{ application.abstain.count }}</button></a>
    <a href="{% url 'festival_app:dislike' application.slug %}"><button type="button" class="btn btn-primary">Не нравится {{ application.dislikes.count }}</button></a>
</div>
{% endif %}
{% endblock content %}

festival_app/templates/view-app-detail-musican.html
{% extends 'base.html' %}
{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'css/app.css' %}">

<div class="mu-app">
    <p>Имя группы или музыканта: {{ application.name }}</p>
    <p>Формат выступления: {{ application.get_format_display }}</p>
    <p>Подробное описание: <br> {{ application.description }}</p>
    <p>Телефон для связи: {{ application.phone }}</p>
    <p>Желаемая сцена: {{ application.get_scene_display }}</p>
    <p>Желаемый день выступления: {{ application.get_performance_day_display }}</p>
    <p>Пожелания: {{ application.wishes }} </p>
    {% if application.denied %}
    <p>Состояние заявки: Отказ. <br> Но вы не расстраивайтесь, вы можете попробовать в следующий раз!</p>
    {% elif application.accepted %}
    <p>Состояние заявки: Одобрена. <br> В ближайшее время с вами свяжется наш менеджер. Если возникнут вопросы
    обращайтесь по телефону: +79********
    </p>
    {% else %}
    <p>Состояние заявки: На рассмотрении. </p>
    {% endif %}
</div>


{% endblock content %}

festival_app/templates/view-applications.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static "css/app.css" %}">
<div class="container">
    <div class="row">
        {% if sum_unrw_apps != 0 %}
        <div class="col-sm">
            <h2> Нерасмотренные заявки </h2>
                <div class="apps">
                    {% for app in unreviewed_apps %}
                    <a href="{% url 'festival_app:view-app-censor' app.slug %}">
                        <h4> Заявка №{{ app.id}} </h4>
                        <p>Имя группы/исполнителя: {{ app.name }}</p>
                        <p>Желаемый день: {{ app.get_performance_day_display }}</p>
                        <p>Формат выступления: {{ app.get_format_display }}</p>
                    </a>
                    {% endfor %}
                </div>
        </div>
        {% endif %}
        <div class="col-sm">
            <h2>Одобренные заявки</h2>
                <div class="apps">
                    {% for app in accepted_apps %}
                    <a href="{% url 'festival_app:view-app-censor' app.slug %}">
                        <h4> Заявка №{{ app.id}} </h4>
                        <p>Имя группы/исполнителя: {{ app.name }}</p>
                        <p>Желаемый день: {{ app.get_performance_day_display }}</p>
                        <p>Формат выступления: {{ app.get_format_display }}</p>
                    </a>
                    {% endfor %}
                </div>
        </div>
    </div>
</div>
<hr>
<nav aria-label="Пагинация">
    <ul class="pagination justify-content-lg-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Назад</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Назад</a>
        </li>
        {% endif %}


        {% for n in page_obj.paginator.page_range %}
            {% if page_obj.number == n %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ n }}">{{ n }}<span class="sr-only">(current)</span></a>
                </li>
            {%  elif n > page_obj.number|add:-3 and n < page_obj.number|add:3 %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ n }}">{{ n }}</a>
                </li>
            {% endif %}
        {% endfor %}


        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Вперед</a>
        </li>
        {% endif%}
    </ul>
</nav>
{% endblock content %}

festival_app/templates/way.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/app.css' %}">

<div class="way">
    <h2>Как доехать.</h2>
    <p>Если вы из Краснодарского края, то вам будет легко добраться.
        Мы находимся за новым Краснодаром, по адресу Лесная 64, по указателям вы попадете к сцене "Арбузик".
        Если вам нужно на другую сцену, то ежайте дальше по указателям. 
        Если вы из другого региона, то вы можете подать заявку ТЦ и доехать на нашем автобусе. 
        У вас еще есть вопросы? Позвоните нам по телефону +79*********.
    </p>
</div>


{% endblock content %}