festival/urls.py
from django.contrib import admin
from django.urls import path, include
from festival_app.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('', include('user_profiles.urls', namespace='user_profiles')),
    path('', include('festival_app.urls', namespace='festival_app')),
]

festival_app/urls.py
from django.urls import path
from festival_app.views import CreateApplication, ViewApplications, AppAcceptToggle, AppDeniedToggle, ErrorView, WayView,\
    ViewApplicationDetailCensor, AppLikeToggle, AppDislikeToggle, ViewApplicationDetailMusican, AppAbstainToggle

app_name = 'festival_app'

urlpatterns = [
    path('application-create', CreateApplication.as_view(), name='application-create'),
    path('view-applications', ViewApplications.as_view(), name='view-applications'),
    path('view-app-musican/<slug:slug>/', ViewApplicationDetailMusican.as_view(), name='view-app-musican'),
    path('view-app-censor/<slug:slug>/', ViewApplicationDetailCensor.as_view(), name='view-app-censor'),
    path('view-app-censor/<slug:slug>/abstain', AppAbstainToggle.as_view(), name='abstain'),
    path('view-app-censor/<slug:slug>/like', AppLikeToggle.as_view(), name='like'),
    path('view-app-censor/<slug:slug>/dislike', AppDislikeToggle.as_view(), name='dislike'),
    path('view-app-censor/<slug:slug>/accept', AppAcceptToggle.as_view(), name='accepted'),
    path('view-app-censor/<slug:slug>/denied', AppDeniedToggle.as_view(), name='denied'),
    path('error', ErrorView.as_view(), name='error'),
    path('way', WayView.as_view(), name='way'),
]

user_profiles/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from user_profiles.views import RegisterView
app_name = 'user_profiles'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='register.html',
                                           success_url=reverse_lazy('festival_app:application-create')),
         name='register'),
]

festival_app/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from slugify import slugify

from user_profiles.models import UserProfile



RED = 'RD'
BLUE = 'BL'
WATERMELON = 'WM'

SCENE_CHOICES = [
    (RED, 'Красная'),
    (BLUE, 'Синяя'),
    (WATERMELON, 'Арбузик'),
]

class Application(models.Model):
    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'

    GROUP = 'GR'
    SOLO = 'SO'

    FORMAT_CHOICES = [
        (GROUP, 'Группа'),
        (SOLO, 'Сольное выступление'),
    ]

    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, allow_unicode=True, max_length=30)
    phone = models.CharField(max_length=12, verbose_name='Телефон')

    format = models.CharField(max_length=2, choices=FORMAT_CHOICES, verbose_name='Формат выступления')
    name = models.CharField(max_length=30, verbose_name='Имя группы или исполнителя', unique=True)
    description = models.TextField(verbose_name='Описание')
    likes = models.ManyToManyField(UserProfile, blank=True, related_name='likes', verbose_name='Нравится')
    dislikes = models.ManyToManyField(UserProfile, blank=True, related_name='dislikes', verbose_name='Не нравится')
    abstain = models.ManyToManyField(UserProfile, blank=True, related_name='abstain', verbose_name='Воздерживаюсь')
    rating = models.IntegerField(default=0, verbose_name='Рейтинг')
    accepted = models.BooleanField(default=False, verbose_name='Одобрено')
    denied = models.BooleanField(default=False, verbose_name='Отказано')
    scene = models.CharField(max_length=2, choices=SCENE_CHOICES, verbose_name='Желаемая сцена')

    FRIDAY = 'FR'
    SATURDAY = 'SA'

    DAY_CHOICES = [
        (FRIDAY, 'Пятница'),
        (SATURDAY, 'Суббота'),
    ]

    performance_day = models.CharField(max_length=2, choices=DAY_CHOICES, verbose_name='Желаемый день выступления')
    wishes = models.CharField(max_length=250, blank=True, verbose_name='Пожелания')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('festival_app:view-app-censor', kwargs={'slug': self.slug})


# Автоматическая генерация и установка слагов для заявок.


def create_slug(instance, new_slug=None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = slugify(new_slug)
    qs = Application.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_app_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_app_receiver, sender=Application)


# Автоматический подсчет рейтинга после каждого лайка/дизлайка.
def count_rating(slug):
    app = Application.objects.get(slug=slug)
    app.rating = app.likes.count() - app.dislikes.count()
    app.save()


# Автоматический вердикт для заявки, когда сумма голосов равна количеству цензоров. ( То есть проголосовали
# все цензоры )
def count_votes(slug):
    app = Application.objects.get(slug=slug)
    app_votes = app.likes.count() + app.dislikes.count() + app.abstain.count()
    censors_count = UserProfile.objects.filter(type='CE').count()
    if app_votes == censors_count:
        if app.likes.count() > app.dislikes.count():
            app.accepted = True
            app.save()
        if app.dislikes.count() > app.likes.count():
            app.denied = True
            app.save()
        if app.likes.count() == app.dislikes.count():
            app.denied = True
            app.save()


class Scene(models.Model):

    class Meta:
        verbose_name = 'Сцена'
        verbose_name_plural = 'Сцены'

    title = models.CharField(max_length=2, choices=SCENE_CHOICES, verbose_name='Название сцены')
    description = models.CharField(max_length=300, verbose_name='Описание сцены')
    first_day_afternoon = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день днём')
    first_day_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день вечером')
    first_day_late_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день поздним '
                                                                             'вечером')
    second_day_afternoon = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день днём')
    second_day_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день вечером')
    second_day_late_evn = models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день поздним '
                                                                              'вечером')

    def __str__(self):
        return self.title

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% bootstrap_css %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.css'%}">
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Глухие Урочища</title>
</head>

<body style="background: url('{% static 'images/gl.jpeg' %}') no-repeat;">
  <div class="sidenav">
    <a href="{% url 'home' %}">Урочища</a>
    {% if user.is_authenticated and app %}
    <a href="{% url 'festival_app:view-app-musican' app.slug %}">Ваша заявка</a>
    {% endif %}
    {% if user.is_anonymous %}
    <a href="{% url 'user_profiles:login' %}">Войти</a>
    {% endif %}
    {% if censor %}
    <a href="{% url 'festival_app:view-applications' %}">Проверить заявки</a>
    {% endif %}
    <a href="{% url 'festival_app:way' %}">Как доехать</a>
    <a href="{% url 'festival_app:application-create' %}">Подать заявку</a>
    {% if user.is_authenticated %}
    <a href="{% url 'user_profiles:logout' %}">Выйти</a>
    {% endif %}
  </div>
  {% block content %}
  <div class="container-fluid">
    <div class="main">
      <div class="scenes">
        <h2>Что такое Глухие Урочища?</h2>
        <p>Глухие урочища - это фестиваль для любительный активной музыки и отдыха. Изначально этот фестиваль провоидлся несколько раз в году,
          но благодаря поддержки со стороны поситителей, а так же правительства нашего края, мы проводим фестиваль каждыую пятницу и субботу. 
          Более подробную информацию о сценах и кол-ве музыкантов вы можете узнать в таблице ниже. Где мы находимся, вы можете узнать в разделе "Как доехать".
        </p>
        <table class="table table-bordered table-dark">
          <thead>
            <tr>
              <th scope="col">Название сцены</th>
              <th scope="col">Описание</th>
              <th scope="col">Количество групп в 1-ый день днём</th>
              <th scope="col">Количество групп в 1-ый день вечером</th>
              <th scope="col">Количество групп в 1-ый день поздним вечером</th>
              <th scope="col">Количество групп в 2-ой день днём</th>
              <th scope="col">Количество групп в 2-ой день вечером</th>
              <th scope="col">Количество групп в 2-ой день поздним вечером</th>
            </tr>
          </thead>
          <tbody>
            {% for scene in scenes %}
            <tr>
              <td>{{ scene.get_title_display }}</td>
              <td>{{ scene.description }}</td>
              <td>{{ scene.first_day_afternoon }}</td>
              <td>{{ scene.first_day_evn }}</td>
              <td>{{ scene.first_day_late_evn }}</td>
              <td>{{ scene.second_day_afternoon }}</td>
              <td>{{ scene.second_day_evn }}</td>
              <td>{{ scene.second_day_late_evn }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% endblock content %}
</body style="background: url('{% static 'images/gl.jpeg' %}');">

</html>