festival/urls.py
from django.contrib import admin
from django.urls import path, include
from festival_app.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('', include('user_profiles.urls', namespace='user_profiles')),
    path('', include('festival_app.urls', namespace='festival_app')),
]

user_profiles/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from user_profiles.views import RegisterView
app_name = 'user_profiles'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='register.html',
                                           success_url=reverse_lazy('festival_app:application-create')),
         name='register'),
]

user_profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


class UserProfile(models.Model):
    class Meta:
        verbose_name = 'Пользовательский профиль'
        verbose_name_plural = 'Пользовательские профили'

    MUSICAN = 'MU'
    CENSOR = 'CE'
    ADMIN = 'AD'

    USER_TYPE_CHOICES = [
        (MUSICAN, 'Музыкант'),
        (CENSOR, 'Цензор'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    type = models.CharField(max_length=2, choices=USER_TYPE_CHOICES, verbose_name='Тип пользователя', default=MUSICAN)

    def __str__(self):
        return self.user.username


# Автоматическое создание профиля, после регистрации.

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)


post_save.connect(create_user_profile, sender=User)

user_profiles/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

user_profiles/views.py
from django.contrib.auth import login, authenticate
from django.views.generic import FormView
from user_profiles.forms import RegistrationForm


class RegisterView(FormView):
    form_class = RegistrationForm

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        login(self.request, authenticate(username=username, password=raw_password))
        return super(RegisterView, self).form_valid(form)

user_profiles/templates/login.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/auth.css' %}">

<div class="container-fluid">
	<div class='login'>
		<form method="post">
			{% csrf_token %}
			{% bootstrap_form form %}
			<button class="btn btn-primary" style="width:100%">Войти</button>
		</form>
		<p>У вас нет аккаунта? <a href="{% url 'user_profiles:register' %}">Регистрация.</a></p>
	</div>
</div>

{% endblock content %}

user_profiles/templates/logout.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Выйти">
</form>
{% endblock content %}

user_profiles/templates/register.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap4 %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/auth.css' %}">

<div class="container-fluid">
	<div class='register'>
		<form method="post">
			{% csrf_token %}
			{% bootstrap_form form %}
			<button class="btn btn-primary" style="width:100%">Регистрация</button>
		</form>
	</div>
</div>
{% endblock content %}